name: EPUB Validation

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run comprehensive validation
      run: npm run ci:full
      
    - name: Check file organization and assets
      run: |
        echo "Checking EPUB file organization..."
        ls -la
        echo "OEBPS directory:"
        ls -la OEBPS/ || echo "No OEBPS directory found"
        echo "Images directory:"
        ls -la OEBPS/images/ || echo "No images directory found"
        echo "Styles directory:"
        ls -la OEBPS/styles/ || echo "No styles directory found"
        
    - name: Lint XHTML files
      run: |
        echo "Checking for common issues in OEBPS/text..."
        echo "Files with missing alt attributes:"
        grep -r 'img.*src=' OEBPS/text/*.xhtml | grep -v 'alt=' || echo "None found"
        echo "Files missing EPUB namespace:"
        grep -L 'xmlns:epub="http://www.idpf.org/2007/ops"' OEBPS/text/*.xhtml || echo "None found"
        
    - name: Generate validation report
      run: |
        echo "# EPUB Validation Report" > validation-report.md
        echo "Generated on: $(date)" >> validation-report.md
        echo "" >> validation-report.md
        echo "## File Structure" >> validation-report.md
        echo "\`\`\`" >> validation-report.md
        find OEBPS -name "*.xhtml" -o -name "*.css" -o -name "*.png" -o -name "*.JPEG" | sort >> validation-report.md
        echo "" >> validation-report.md
        echo "## Performance Metrics" >> validation-report.md
        if [ -f "performance-metrics-report.md" ]; then
          cat performance-metrics-report.md >> validation-report.md
        fi
        echo "\`\`\`" >> validation-report.md
        
    - name: Upload reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: epub-reports
        path: |
          validation-report.md
          performance-metrics-report.md
          asset-validation-report.md
          asset-optimization-report.md
          multi-format-validation-report.md
          epub-integration-test-report.md
          path-reference-regression-report.md